config/routes.rb
OfficePuraErp::Application.routes.draw do

  get "debug", to: "dashboards#debug"

  get 'approvals' => 'approvals#index'

  resources :legalities do
    member do
      get 'enable'
      get 'disable'
    end
  end

  devise_for :users,
    :controllers => { sessions: 'devise/sessions' },
    :path => "user",
    :path_names => {
      :sign_in => 'login',
      :sign_out => 'logout'
    }

  resources :routetrains do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :routeships do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :customers do
    member do
      get 'enable'
      get 'disable'
      get 'addroute'
      get 'addcontract'
      get 'clone'
      get 'gm_approve'
    end
    collection do
      get "customer_terms" => "customers#customer_terms"
    end
  end

  resources :customernotes, only: [:create, :update, :destroy]

  get 'contracts/addnew' => 'contracts#addnew'
  resources :contracts do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :suppliers do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :staffs do
    member do
      get 'enable'
      get 'disable'
    end
  end

  get 'drivers/blacklist' => 'drivers#blacklist'
  get 'drivers/history' => 'drivers#history'

  resources :drivers do
    member do
      get 'enable'
      get 'disable'
      get 'blacklisted'
      get 'whitelisted'
    end

    collection do
      get "create_bank_expense_group"
      get "clone"
      get "save_clone"
    end
  end
  
  get 'helpers/blacklist' => 'helpers#blacklist'
  resources :helpers do
    member do
      get 'enable'
      get 'disable'
    end

    collection do
      get "create_bank_expense_group"
    end
  end

  resources :isotanks do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :containers do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :operators do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :products do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :warehouses do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :productgroups do
    member do
      get 'enable'
      get 'disable'
    end
  end

  get 'routes/addnew' => 'routes#addnew'
  resources :routes do
    member do
      get 'enable'
      get 'disable'
      get 'copy'
      get 'approve'
      get 'reject'
      get 'revision'
    end
    collection do
      get "index_api"
      get "index_api_detailed"
      get "managements"
    end
  end

  resources :claimmemos do
    member do
      get 'spv_approve'
      get 'load_approve'
      get 'unload_approve'
      get 'marketing_approve'
      get 'gm_approve'
    end
  end

  get 'quotationgroups/reports' => 'quotationgroups#reports'

  resources :quotationgroups do
    member do
      get "print"
      get "approve_customer"
      get "approve_sent"
      get "approve_confirm"
      get "approve_review"
    end
    collection do
      get 'confirmed' => 'quotationgroups#indexconfirm'
      get "getcustomer/:value" => 'quotationgroups#getcustomer'
      get "getquotation/:id" => 'quotationgroups#getquotation'
      get "index_api"
      get "indexconfirm_api"
      post "confirmation"
    end
  end

  get 'quotations/confirmed' => 'quotations#indexconfirm'
  resources :quotations do
    member do
      get 'enable'
      get 'disable'
      get "copy"
    end
    collection do
      get "index_api"
      get "indexconfirm_api"
      post "confirmation"
    end
  end
 
  match 'vehicles/index_asset' => 'vehicles#index_asset'
  post 'vehicles/update_asset' => 'vehicles#update_asset'
  get 'vehicles/history' => 'vehicles#history'

  resources :vehicles do
    member do
      get 'enable'
      get 'disable'
      get 'edit_asset'
    end
  end

  resources :vehiclelogs

  match 'vehiclelogs/new/:vehicle_id' => 'vehiclelogs#new'
  match "vehicledates" => "vehiclelogs#vehicledates"

  resources :vehiclegroups do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :assets do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :commodities do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :assetgroups

  resources :allowances
  post 'allowances/updateitems' => 'allowances#updateitems'

  resources :tirebudgets
  post 'tirebudgets/updateitems' => 'tirebudgets#updateitems'

  resources :settings

  match 'generalexpenses/new(/:officeexpense_id)' => 'generalexpenses#new'
  post 'generalexpenses/create' => 'generalexpenses#create'
  resources :generalexpenses do
    member do
      get 'enable'
      get 'disable'
    end
  end

  get 'officeexpenses/getofficeexpensegroup/:group_id' => 'officeexpenses#getofficeexpensegroup'
  get 'officeexpenses/getbankexpensegroup/:bankgroup_id' => 'officeexpenses#getbankexpensegroup'

  get 'bankinvoices/getbankexpensegroup/:group_id' => 'bankinvoices#getbankexpensegroup'

  get 'bankexpenses/getbankexpensegroupdebit/:group_id' => 'bankexpenses#getbankexpensegroupdebit'
  get 'bankexpenses/getbankexpensegroupcredit/:group_id' => 'bankexpenses#getbankexpensegroupcredit'

  get 'events/get_event_by_customer/:customer_id' =>'events#get_event_by_customer'
  get 'events/getdodetail' => 'events#getdodetail'

  resources :mechaniclogs do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :shipexpenses do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :officeexpenses do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :officebankexpenses

  resources :officeexpensegroups do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :bankexpenses do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :bankinvoices do
    member do
      get 'verified'
      get 'disable'
      get 'print'
    end
  end

  resources :bankexpensegroups do
    member do
      get 'enable'
      get 'disable'
      get 'inReportEnable'
      get 'inReportDisable'
    end
  end

  resources :offices do
    member do
      get 'enable'
      get 'disable'
    end
  end

  get 'invoices/printspk/:id' => 'invoices#printspk'

  match 'invoices/add_ship' => 'invoices#indexaddship'
  match 'invoices/add_ship/:invoice_id' => 'invoices#add_ship'
  post 'invoices/updateship/' => 'invoices#updateship'

  match 'invoices/add_train' => 'invoices#indexaddtrain'
  match 'invoices/add_train/:invoice_id' => 'invoices#add_train'
  post 'invoices/updatetrain/' => 'invoices#updatetrain'

  get 'invoices/add_container' => 'invoices#indexaddcontainer'
  get 'invoices/add_container/:invoice_id' => 'invoices#add_container'
  post 'invoices/updatecontainer/' => 'invoices#updatecontainer'

  match 'invoices/add_weight' => 'invoices#indexaddweight'
  match 'invoices/add_weight/:invoice_id' => 'invoices#add_weight'
  post 'invoices/updateaddweight/' => 'invoices#updateaddweight'

  match 'invoices/updatedata/:invoice_id' => 'invoices#updatedata', as: 'updatedata'
  post 'invoices/updatedatabkk/' => 'invoices#updatedatabkk'

  #kosonganProduktif
  match 'invoices/kosongan_prod' => 'invoices#kosongan_prod'
  match 'invoices/add_kosongan' => 'invoices#add_kosongan'
  post 'invoices/createkosongan/' => 'invoices#createkosongan', as: 'createkosongan'

  #kosongan non Produktif
  match 'invoices/kosongan_approval' => 'invoices#kosongan_approval'
  match 'invoices/kosongan_approve(/:invoice_id)' => 'invoices#kosongan_approve'
  post 'invoices/kosongan_confirm/' => 'invoices#kosongan_confirm'

  match 'invoices/trainrequest' => 'invoices#indextrainrequest'

  match 'invoices/indexadd' => 'invoices#indexadd'
  match 'invoices/add(/:invoice_id)' => 'invoices#add'
  match 'invoices/indexinvoicetrain' => 'invoices#indexinvoicetrain'
  match 'invoices/adddriver(/:invoice_id)' => 'invoices#adddriver'
  post 'invoices/updateinvoice/' => 'invoices#updateinvoice'
  match 'invoices/print/:invoice_id' => 'invoices#print'
  match 'invoices/form_event' => 'invoices#form_event'
  match 'invoices/kosongan' => 'invoices#kosongan'

  match 'invoices/newupdated' => 'invoices#new_updated', as: "newupdate_invoice"
  match 'invoices/isotank' => 'invoices#isotank', as: "invoice_isotank"
  match 'invoices/kereta' => 'invoices#kereta', as: "invoice_train"
  match 'invoices/kapal' => 'invoices#kapal', as: "invoice_ship"
  match 'invoices/:invoice_id/editupdated' => 'invoices#edit_updated'

  resources :invoices do
    member do
      get 'enable'
      get 'disable'
      get 'step2'
      get 'confirmation'
      get 'printversion'
      get 'cancelmarketing'
    end

    collection do
      get "isotank"
    end
  end

  resources :invoicetrains

  resources :invoicetests do
    member do
      get 'enable'
      get 'disable'
      get 'step2'
      get 'confirmation'
      get 'printversion'
    end
  end

  resources :eventmemos do
    member do
      get 'enable'
      get 'disable'

      get "print"
    end
  end

  resources :eventcleaningmemos do
    member do
      get 'enable'
      get 'disable'
      get "print"
    end
  end

  resources :operators do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :trainexpenses do
    collection do
      get 'download_excel'
    end
    member do
      get 'enable'
      get 'disable'
      get "print"
    end
  end

  resources :insurancevendors do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :insuranceexpenses do
    member do
      get 'enable'
      get 'disable'
      get "print"
    end
  end

  match 'vendors/driver_activities' => 'vendors#driver_activities'

  resources :vendors do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :vendorvehicles do
    member do

app/models/staff.rb
class Staff < ActiveRecord::Base

  # Setup accessible (or protected) attributes for your model
  has_many :productorders
  has_many :users

  attr_accessible :enabled, :name, :email,
					:address, :city, :phone, :mobile, :driver_licence, :driver_licence_expiry, :id_card, :id_card_expiry,
					:start_working, :description, :min_wages, :status, :salary, :terms_of_payment_in_days, :deleted, :office_id,
          :family_card_number, :family_status, :emergency_contact, :origin
          
  scope :active, lambda {where(:enabled => true, :deleted => false)}  					

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
	include ApplicationHelper
	layout "application"
  before_filter :authenticate_user!, :set_section, :set_role

  def set_section
    @section = "masters"
    @where = "staffs"
    @statuses = ["Tetap", "Kontrak", "Resign"]
  end

  def set_role
    @user_role = 'Admin HRD'
  end

  def index
    role = cek_roles @user_role
    if role

      @status = params[:status]

      @staffs = Staff.order('name')

      if @status.present? and @status != ''
          @staffs = @staffs.where("status = ?", @status)
      end

      respond_to :html
    else
      redirect_to root_path()
    end
    
  end

  def new
    @staff = Staff.new
    @staff.enabled = true
  end

  def edit
    @staff = Staff.find(params[:id])
    @staff.salary = @staff.salary.to_i
    @staff.driver_licence_expiry = @staff.driver_licence_expiry.strftime('%d-%m-%Y') if !@staff.driver_licence_expiry.blank?
    @staff.id_card_expiry = @staff.id_card_expiry.strftime('%d-%m-%Y') if !@staff.id_card_expiry.blank?
    @staff.start_working = @staff.start_working.strftime('%d-%m-%Y') if !@staff.start_working.blank?
  end

  def create
    inputs = params[:staff]
    @staff = Staff.new(inputs)
    @staff.email = @staff.email.downcase

    if @staff.save
      redirect_to(edit_staff_url(@staff), :notice => 'Data Staff sukses di tambah.')
    else
      to_flash(@staff)
      render :action => "new"
    end
  end

  def update
    inputs = params[:staff]
    @staff = Staff.find(params[:id])

    if @staff.update_attributes(inputs)
      @staff.email = @staff.email.downcase
      @staff.save
      redirect_to(edit_staff_url(@staff), :notice => 'Data Staff sukses di simpan.')
    else
      to_flash(@staff)
      render :action => "edit"
    end
  end

  def destroy
    @staff = Staff.find(params[:id])
    @staff.deleted = true
    @staff.save 
    redirect_to(staffs_url)
  end  
  
  def enable
    @staff = Staff.find(params[:id])
    @staff.update_attributes(:enabled => true)
    redirect_to(staffs_url)
  end
  
  def disable
    @staff = Staff.find(params[:id])
    @staff.update_attributes(:enabled => false)
    redirect_to(staffs_url)
  end
end

app/views/staffs/_form.html.erb
<%= form_for(@staff) do |f| %>
	<div class="field-row first">
    <%= f.label :name, "Nama" %>
    <%= f.text_field :name %>
	</div>

  <div class="field-row">
    <%= f.label :email, "Email" %>
    <%= f.text_field :email %>
  </div>

  <div class="field-row">
    <%= f.label :address, "Alamat" %>
    <%= f.text_field :address %>
  </div>

  <div class="field-row">
    <%= f.label :city, "Kota" %>
    <%= f.text_field :city %>
  </div>

  <div class="field-row">
    <%= f.label :phone, "No. Telp" %>
    <%= f.text_field :phone, :class => 'half left' %>
    <%= f.label :mobile, "No. HP", :class => 'middle' %>
    <%= f.text_field :mobile, :class => 'half left' %>
  </div>

  <div class="field-row" style="display: none;">
    <%= f.label :driver_licence, "SIM" %>
    <%= f.text_field :driver_licence, :class => 'half left' %>
    <%= f.label :driver_licence_expiry, "Expired", :class => 'middle' %>
    <%= f.text_field :driver_licence_expiry, :class => 'half left date-picker' %>
  </div>

  <div class="field-row">
    <%= f.label :id_card, "KTP" %>
    <%= f.text_field :id_card, :class => 'half left' %>
    <%= f.label :id_card_expiry, "Expired", :class => 'middle' %>
    <%= f.text_field :id_card_expiry, :class => 'half left date-picker' %>
  </div>

  <div class="field-row">
    <%= f.label :family_card_number, "No. KK" %>
    <%= f.text_field :family_card_number, :class => 'half left' %>
    <%= f.label :family_status, "Status Keluarga", :class => 'middle' %>
    <%= f.text_field :family_status, :class => 'half left' %>
  </div>

  <div class="field-row">
    <%= f.label :emergency_contact, "Kontak Darurat" %>
    <%= f.text_field :emergency_contact, :class => 'half left' %> 
  </div>

  <div class="field-row">
    <%= f.label :salary, "Gaji Pokok" %>
    <%= f.text_field :salary, :class => 'half left' %>
    <%= f.label :min_wages, "Jamsostek", :class => 'middle' %>
    <%= f.text_field :min_wages, :class => 'half left' %>
  </div>

  <div class="field-row">
    <%= f.label :start_working, "Mulai Kerja" %>
    <%= f.text_field :start_working, :class => 'half left date-picker' %>
    <%= f.label :status, :class => 'middle' %>
    <%= f.select :status, options_for_select(@statuses.collect {|w| [w, w]}, @staff.status), {}, { :class => 'half left chzn-select' } %>
  </div>

  <div class="field-row" style="display:none">
    <%= f.label :terms_of_payment_in_days, "Batas Hutang" %>
    <%= f.text_field :terms_of_payment_in_days, :class => 'half' %>
    <span>Hari</span>
  </div>

  <div class="field-row">
    <%= f.label :description, "Keterangan" %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit "Tambah Data", :class => 'left' if checkrole 'Admin HRD' %>
    <a class="back left" href="<%=staffs_path%>">Kembali ke Index</a>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<%= render "shared/header" %>

<div id="nav">
	<%= render "shared/nav" %>
</div>

<div id="main">

	<div id="content-full">
		<a class="btn-txt cancel" href="<%=staffs_path%>"><i class="icon-remove"></i> Batal</a>

		<h1>Master / <a href="<%=staffs_path%>">Staff</a> / Edit <strong title="<%=@staff.name%>"><%= @staff.name %></strong></h1>

		<br class="clearfix" />

		<%= render "form" %>

		<br class="clearfix" />

	</div>

</div>

app/views/staffs/index.html.erb
<%= render "shared/header" %>

<div id="nav">
	<%= render "shared/nav" %>
</div>

<div id="main">
	
	<div id="content-full">
		<% if checkrole 'Admin HRD' %>
		<a class="btn print" href="<%=new_staff_path%>"><i class="icon-plus-sign"></i> &nbsp;Tambah</a>
		<% end %>
		<h1>Master / <a href="<%=staffs_path%>">Staff</a> / Index</h1>

		<%= render 'default/toggle_deleted_checkbox' %>

		<br class="clearfix" />
		<br class="clearfix" />

		<div id="filter" style="padding: 5px 10px 5px 10px;">
			<form id="filterform" name="filterform" action="" method="get">
			<div class="field-row continue">

				<label for="status" style="float:none">Status</label>
				<select name="status" class="half combo_route" style="margin-top: 0.25rem;">
				<option value="">Semua</option>
					<% ["Tetap", "Kontrak", "Resign"].each do |type| %>
					<option <%= type == params[:status] ? 'selected' : '' %>><%=type%></option>
					<% end %>
				</select> 
 
				<input class="submit" type="submit" value="Filter" />
			</div>
			</form>
		</div>

		<br class="clearfix" />

		<table class="row-view tablesorter">
			<thead>
			<tr>
				<th>Nama</th>
				<th>Kota</th>
				<th>Telp</th>
				<th>Status</th>
				<th width="60" class="{sorter: false}">Aktif</th>
				<th width="60" class="{sorter: false}"></th>
			</tr>
			</thead>

			<tbody>
			<% @staffs.each do |staff| %>
			<% if staff.deleted %>
				<% if current_user.adminrole %>
				<tr class="deleted">
					<td><%= staff.name %></td>
					<td><%= staff.city %></td>
					<td><%= !staff.phone.blank? ? staff.phone : staff.mobile %></td>
					<td><%= staff.status %></td>
					<% if staff.enabled %>
					<td><%= link_to '&#xf058;'.html_safe, 'javascript: void();', :class => 'enabled tipsy', :title => 'Aktif' %></td>
					<% else %>
					<td><%= link_to '&#xf057;'.html_safe, 'javascript: void();', :class => 'disabled tipsy', :title => 'Tidak Aktif' %></td>
					<% end %>
					<td class="right" width="60">&nbsp;</td>
				</tr>
				<% end %>
			<% else %>
				<% if checkrole 'Admin HRD' %>
				<tr>
					<td><%= link_to staff.name, edit_staff_path(staff) %></td>
					<td><%= staff.city %></td>
					<td><%= !staff.phone.blank? ? staff.phone : staff.mobile %></td>
					<td><%= staff.status %></td>
					<% if staff.enabled %>
					<td><%= link_to '&#xf058;'.html_safe, disable_staff_path(staff), :class => 'enabled tipsy', :title => 'Non Aktifkan' %></td>
					<% else %>
					<td><%= link_to '&#xf057;'.html_safe, enable_staff_path(staff), :class => 'disabled tipsy', :title => 'Aktifkan' %></td>
					<% end %>
					<td class="right" width="60">
						<%= link_to '&#xf044;'.html_safe, edit_staff_path(staff), :class => "edit tipsy", :title => 'Edit' %> 
						<%= link_to '&#xf00d;'.html_safe, staff, :class => "delete tipsy", :title => 'Hapus', :confirm => 'Apakah anda yakin?', :method => :delete if current_user.owner %>
					</td>
				</tr>
				<% else %>
				<tr>
					<td><%= staff.name %></td>
					<td><%= staff.city %></td>
					<td><%= !staff.phone.blank? ? staff.phone : staff.mobile %></td>
					<td><%= staff.status %></td>
					<% if staff.enabled %>
					<td><%= link_to '&#xf058;'.html_safe, 'javascript: void();', :class => 'enabled tipsy', :title => 'Aktif' %></td>
					<% else %>
					<td><%= link_to '&#xf057;'.html_safe, 'javascript: void();', :class => 'disabled tipsy', :title => 'Tidak Aktif' %></td>
					<% end %>
					<td class="right" width="60">&nbsp;</td>
				</tr>
				<% end %>
			<% end %>
			
			<% end %>	
			</tbody>
		
		</table>

		<% if checkrole 'Admin HRD' %>
		<div class="actions">
			<a class="btn-txt right" href="<%=new_staff_path%>"><i class="icon-plus-sign"></i> &nbsp;Tambah</a>
		</div>
		<% end %>

		<br class="clearfix" />

	</div>

</div>

app/views/staffs/new.html.erb
<%= render "shared/header" %>

<div id="nav">
	<%= render "shared/nav" %>
</div>

<div id="main">
	
	<div id="content-full">
		<a class="btn-txt cancel" href="<%=staffs_path%>"><i class="icon-remove"></i> Batal</a>

		<h1>Master / <a href="<%=staffs_path%>">Staff</a> / Tambah</h1>

		<br class="clearfix" />

		<%= render "form" %>

		<br class="clearfix" />

	</div>

</div>