config/routes.rb
OfficePuraErp::Application.routes.draw do

  get "debug", to: "dashboards#debug"

  get 'approvals' => 'approvals#index'

  resources :legalities do
    member do
      get 'enable'
      get 'disable'
    end
  end

  devise_for :users,
    :controllers => { sessions: 'devise/sessions' },
    :path => "user",
    :path_names => {
      :sign_in => 'login',
      :sign_out => 'logout'
    }

  resources :routetrains do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :routeships do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :customers do
    member do
      get 'enable'
      get 'disable'
      get 'addroute'
      get 'addcontract'
      get 'clone'
      get 'gm_approve'
    end
    collection do
      get "customer_terms" => "customers#customer_terms"
    end
  end

  resources :customernotes, only: [:create, :update, :destroy]

  get 'contracts/addnew' => 'contracts#addnew'
  resources :contracts do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :suppliers do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :staffs do
    member do
      get 'enable'
      get 'disable'
    end
  end

  get 'drivers/blacklist' => 'drivers#blacklist'
  get 'drivers/history' => 'drivers#history'

  resources :drivers do
    member do
      get 'enable'
      get 'disable'
      get 'blacklisted'
      get 'whitelisted'
    end

    collection do
      get "create_bank_expense_group"
      get "clone"
      get "save_clone"
    end
  end
  
  get 'helpers/blacklist' => 'helpers#blacklist'
  resources :helpers do
    member do
      get 'enable'
      get 'disable'
    end

    collection do
      get "create_bank_expense_group"
    end
  end

  resources :isotanks do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :containers do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :operators do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :products do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :warehouses do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :productgroups do
    member do
      get 'enable'
      get 'disable'
    end
  end

  get 'routes/addnew' => 'routes#addnew'
  resources :routes do
    member do
      get 'enable'
      get 'disable'
      get 'copy'
      get 'approve'
      get 'reject'
      get 'revision'
    end
    collection do
      get "index_api"
      get "index_api_detailed"
      get "managements"
    end
  end

  resources :claimmemos do
    member do
      get 'spv_approve'
      get 'load_approve'
      get 'unload_approve'
      get 'marketing_approve'
      get 'gm_approve'
    end
  end

  get 'quotationgroups/reports' => 'quotationgroups#reports'

  resources :quotationgroups do
    member do
      get "print"
      get "approve_customer"
      get "approve_sent"
      get "approve_confirm"
      get "approve_review"
    end
    collection do
      get 'confirmed' => 'quotationgroups#indexconfirm'
      get "getcustomer/:value" => 'quotationgroups#getcustomer'
      get "getquotation/:id" => 'quotationgroups#getquotation'
      get "index_api"
      get "indexconfirm_api"
      post "confirmation"
    end
  end

  get 'quotations/confirmed' => 'quotations#indexconfirm'
  resources :quotations do
    member do
      get 'enable'
      get 'disable'
      get "copy"
    end
    collection do
      get "index_api"
      get "indexconfirm_api"
      post "confirmation"
    end
  end
 
  match 'vehicles/index_asset' => 'vehicles#index_asset'
  post 'vehicles/update_asset' => 'vehicles#update_asset'
  get 'vehicles/history' => 'vehicles#history'

  resources :vehicles do
    member do
      get 'enable'
      get 'disable'
      get 'edit_asset'
    end
  end

  resources :vehiclelogs

  match 'vehiclelogs/new/:vehicle_id' => 'vehiclelogs#new'
  match "vehicledates" => "vehiclelogs#vehicledates"

  resources :vehiclegroups do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :assets do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :commodities do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :assetgroups

  resources :allowances
  post 'allowances/updateitems' => 'allowances#updateitems'

  resources :tirebudgets
  post 'tirebudgets/updateitems' => 'tirebudgets#updateitems'

  resources :settings

  match 'generalexpenses/new(/:officeexpense_id)' => 'generalexpenses#new'
  post 'generalexpenses/create' => 'generalexpenses#create'
  resources :generalexpenses do
    member do
      get 'enable'
      get 'disable'
    end
  end

  get 'officeexpenses/getofficeexpensegroup/:group_id' => 'officeexpenses#getofficeexpensegroup'
  get 'officeexpenses/getbankexpensegroup/:bankgroup_id' => 'officeexpenses#getbankexpensegroup'

  get 'bankinvoices/getbankexpensegroup/:group_id' => 'bankinvoices#getbankexpensegroup'

  get 'bankexpenses/getbankexpensegroupdebit/:group_id' => 'bankexpenses#getbankexpensegroupdebit'
  get 'bankexpenses/getbankexpensegroupcredit/:group_id' => 'bankexpenses#getbankexpensegroupcredit'

  get 'events/get_event_by_customer/:customer_id' =>'events#get_event_by_customer'
  get 'events/getdodetail' => 'events#getdodetail'

  resources :mechaniclogs do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :shipexpenses do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :officeexpenses do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :officebankexpenses

  resources :officeexpensegroups do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :bankexpenses do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :bankinvoices do
    member do
      get 'verified'
      get 'disable'
      get 'print'
    end
  end

  resources :bankexpensegroups do
    member do
      get 'enable'
      get 'disable'
      get 'inReportEnable'
      get 'inReportDisable'
    end
  end

  resources :offices do
    member do
      get 'enable'
      get 'disable'
    end
  end

  get 'invoices/printspk/:id' => 'invoices#printspk'

  match 'invoices/add_ship' => 'invoices#indexaddship'
  match 'invoices/add_ship/:invoice_id' => 'invoices#add_ship'
  post 'invoices/updateship/' => 'invoices#updateship'

  match 'invoices/add_train' => 'invoices#indexaddtrain'
  match 'invoices/add_train/:invoice_id' => 'invoices#add_train'
  post 'invoices/updatetrain/' => 'invoices#updatetrain'

  get 'invoices/add_container' => 'invoices#indexaddcontainer'
  get 'invoices/add_container/:invoice_id' => 'invoices#add_container'
  post 'invoices/updatecontainer/' => 'invoices#updatecontainer'

  match 'invoices/add_weight' => 'invoices#indexaddweight'
  match 'invoices/add_weight/:invoice_id' => 'invoices#add_weight'
  post 'invoices/updateaddweight/' => 'invoices#updateaddweight'

  match 'invoices/updatedata/:invoice_id' => 'invoices#updatedata', as: 'updatedata'
  post 'invoices/updatedatabkk/' => 'invoices#updatedatabkk'

  #kosonganProduktif
  match 'invoices/kosongan_prod' => 'invoices#kosongan_prod'
  match 'invoices/add_kosongan' => 'invoices#add_kosongan'
  post 'invoices/createkosongan/' => 'invoices#createkosongan', as: 'createkosongan'

  #kosongan non Produktif
  match 'invoices/kosongan_approval' => 'invoices#kosongan_approval'
  match 'invoices/kosongan_approve(/:invoice_id)' => 'invoices#kosongan_approve'
  post 'invoices/kosongan_confirm/' => 'invoices#kosongan_confirm'

  match 'invoices/trainrequest' => 'invoices#indextrainrequest'

  match 'invoices/indexadd' => 'invoices#indexadd'
  match 'invoices/add(/:invoice_id)' => 'invoices#add'
  match 'invoices/indexinvoicetrain' => 'invoices#indexinvoicetrain'
  match 'invoices/adddriver(/:invoice_id)' => 'invoices#adddriver'
  post 'invoices/updateinvoice/' => 'invoices#updateinvoice'
  match 'invoices/print/:invoice_id' => 'invoices#print'
  match 'invoices/form_event' => 'invoices#form_event'
  match 'invoices/kosongan' => 'invoices#kosongan'

  match 'invoices/newupdated' => 'invoices#new_updated', as: "newupdate_invoice"
  match 'invoices/isotank' => 'invoices#isotank', as: "invoice_isotank"
  match 'invoices/kereta' => 'invoices#kereta', as: "invoice_train"
  match 'invoices/kapal' => 'invoices#kapal', as: "invoice_ship"
  match 'invoices/:invoice_id/editupdated' => 'invoices#edit_updated'

  resources :invoices do
    member do
      get 'enable'
      get 'disable'
      get 'step2'
      get 'confirmation'
      get 'printversion'
      get 'cancelmarketing'
    end

    collection do
      get "isotank"
    end
  end

  resources :invoicetrains

  resources :invoicetests do
    member do
      get 'enable'
      get 'disable'
      get 'step2'
      get 'confirmation'
      get 'printversion'
    end
  end

  resources :eventmemos do
    member do
      get 'enable'
      get 'disable'

      get "print"
    end
  end

  resources :eventcleaningmemos do
    member do
      get 'enable'
      get 'disable'
      get "print"
    end
  end

  resources :operators do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :trainexpenses do
    collection do
      get 'download_excel'
    end
    member do
      get 'enable'
      get 'disable'
      get "print"
    end
  end

  resources :insurancevendors do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :insuranceexpenses do
    member do
      get 'enable'
      get 'disable'
      get "print"
    end
  end

  match 'vendors/driver_activities' => 'vendors#driver_activities'

  resources :vendors do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :vendorvehicles do
    member do

app/controllers/approvals_controller.rb
class ApprovalsController < ApplicationController
	include ApplicationHelper
	layout "application"
  before_filter :authenticate_user!, :set_section, :set_role

  def set_section
    @section = "approvals"
    @where = "approvals"
  end

  def set_role
    @user_role = 'Admin Approval, General Manager, Admin Klaim, Admin Approval Klaim, Admin Marketing, Admin Operasional'
  end

  # def index
  #   role = cek_roles @user_role
  #   if role

  #     @new_customers = Customer.active.unverified

  #     # @claimmemos = Claimmemo.active.where('approved = false or approved_by_gm = false')
  #     @claimmemos = Claimmemo.active.where('approved_marketing = false')

  #     @confirmed_quotation = Quotationgroup.active.pluck(:id)
  #     @quotation = Quotation.active.where('quotationgroup_id in (?)', @confirmed_quotation).pluck(:id)
  #     @allowances = Allowance.active.where('driver_trip = money(0)').pluck(:route_id)
  #     # @new_routes = Route.active.where('quotation_id in (?) and id in (?)', @quotation, @allowances)
  #     @new_routes = Route.active
  #       .where('quotation_id IN (?) AND id IN (?) AND created_at >= ?', @quotation, @allowances, 30.days.ago)

  #     @quotationgroups = Quotationgroup.active.where('date >= ?', Date.new(2025, 1, 1)).reorder('date DESC')
  #     @quotationgroups = @quotationgroups.where('confirmed = false')
      
  #     @draft_routes = Route.active.where('approved = false')
  #     respond_to :html
  #   else
  #     redirect_to root_path()
  #   end
  # end

  def index
  role = cek_roles(@user_role)
  if role
    @new_customers = Customer.active.unverified

    @claimmemos = Claimmemo.active.where(:approved_marketing => false)

    # langsung pakai subquery, hindari pluck
    quotationgroups = Quotationgroup.active.select(:id)
    quotations      = Quotation.active.where(:quotationgroup_id => quotationgroups).select(:id)
    allowances      = Allowance.active.where("driver_trip = money(0)").select(:route_id)

    @new_routes = Route.active
      .where("quotation_id IN (?)", quotations)
      .where("id IN (?)", allowances)
      .where("created_at >= ?", 30.days.ago)

    @quotationgroups = Quotationgroup.active
      .where("date >= ?", Date.new(2025, 1, 1))
      .where(:confirmed => false)
      .order("date DESC")

    @draft_routes = Route.active.where(:approved => false)

    respond_to :html
  else
    redirect_to root_path
  end
end

end

app/views/approvals/_claims.html.erb
<table class="row-view tablesorter hasFilters">
  <thead>
    <tr>
      <th>Tgl</th>
      <th>BKK</th>
      <th>Keterangan</th>
      <th>Komoditas</th>
      <th>Muat</th>
      <th>Bongkar</th>
      <th>Susut</th>
      <th>Toleransi</th>
      <th>Beban Susut</th>
      <!-- <th>Harga</th> -->
      <th>Beban Supir</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% if @claimmemos.any? %>
      <% @claimmemos.each do |memo| %>
        <% status = claimmemo_status(memo) %>
        <tr>
          <td><strong><%= memo.date.strftime('%d') %></strong>.<%= memo.date.strftime('%m') %></td>
          <td><%= link_to memo.invoice_id, edit_claimmemo_path(memo, rel: 'approval') %></td>
          <td>
            1 Rit <%= memo.invoice.route.try(:name) %> (<%= memo.invoice.driver.try(:name) %>)
            <%= memo.invoice.invoicetrain ? '= Kereta =' : '' %> 
            <%= memo.invoice.isotank_id.present? ? "Isotank = #{memo.invoice.isotank.try(:isotanknumber)}" : '' %>
            <%= memo.invoice.container_id.present? ? "Kontainer = #{memo.invoice.container.try(:containernumber)}" : '' %>
            <%= memo.invoice.ship_id.present? ? " | #{memo.invoice.ship.try(:name)}" : '' %>
            <%= memo.invoice.user_id.present? ? " | #{memo.invoice.user.try(:username)}" : '' %>
          </td>
          <td><%= memo.invoice.event.try(:commodity).try(:name) %></td>
          <td class="right"><%= memo.weight_gross || 0 %></td>
          <td class="right"><%= memo.weight_net || 0 %></td>
          <td class="right red"><%= memo.shrink || 0 %></td>
          <td class="right"><%= memo.tolerance_total || 0 %></td>
          <td class="right"><%= memo.shrinkage_load || 0 %></td>
          <td class="right"><%= to_currency(memo.total) || 0 %></td>
          <td style="width:80px;">
            <a class="cta" style="background: <%= status[:color] %>; color: <%= status[:text_color] %>; opacity: 1;">
              <%= status[:text] %>
            </a>
          </td>
          <td class="right" width="60">
            <%= link_to '&#xf044;'.html_safe, edit_claimmemo_path(memo, rel: 'approval'), class: "edit tipsy", title: 'Edit' %>
          </td>
        </tr>
      <% end %>
    <% else %> 
      <tr>
        <td colspan='11'>
          Tidak ada data klaim susut baru
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/approvals/_customers.html.erb
<table class="row-view tablesorter hasFilters">
    <thead>
    <tr>
        <th>Nama</th>
        <th>Kota</th>
        <th>Email</th>
        <th>PIC</th>
        <th>No PIC</th>
        <th>PIC Photo</th>
        <th>DP</th>
        <th>KTP</th>
        <th>NPWP</th>
        <th>No. Penawaran&nbsp;&nbsp;</th>
        <th width="60" class="{sorter: false}"></th>
    </tr>
    </thead>

    <tbody>
    <% if @new_customers.any? %>
    
        <% @new_customers.includes(:routes).reorder('name ASC').each do |customer| %>
            <tr>
                <td><%= link_to customer.name, edit_customer_path(customer) %></td>
                <td><%= customer.city %></td>
                <td><%= customer.email %></td>
                <td><%= customer.contact %></td>
                <td><%= customer.phone.present? ? customer.phone : (customer.mobile.present? ? customer.mobile : '') %></td>
                <td><%= customer.images.where("name = 'PIC' and enabled = true").any? ? 'Ya' : 'n/a' %></td>
                <td><%= customer.dp ? 'Ya' : 'n/a' %></td>
                <td><%= customer.images.where("name = 'KTP' and enabled = true").any? ? 'Ya' : 'n/a' %></td>
                <td><%= customer.images.where("name = 'NPWP' and enabled = true").any? ? 'Ya' : 'n/a' %></td>
                <td></td>

                <td class="right" width="60">
                    <%= link_to '&#xf044;'.html_safe, edit_customer_path(customer, rel: 'approval'), :class => "edit tipsy", :title => 'Edit Pelanggan' %>
                </td>
            </tr>
        <% end %>	

    <% else %>	
    
        <tr>
            <td colspan = '11'>
                Tidak ada data pelanggan baru
            </td>
        </tr>

    <% end %>	
    </tbody>

</table>

app/views/approvals/_quotations.html.erb
<table class="row-view">
	<tr>
		<th class="{sorter:true, filter: true}" >TGL</th>
		<th width="200" class="{sorter:true, filter: true}" >Nomor</th>
		<th class="{sorter:true, filter: true}" >Pelanggan</th>
		<th class="{sorter: false, filter: false}" align="right" style="padding-right: 1rem; text-align: right; ">Jurusan</th>
		<th class="{sorter:true, filter: true}" >User</th>
		<th class="{sorter:true, filter: true}" >Status</th>
		<th width="80" class="{sorter: false, filter: false}"></th>
	</tr>

    <% if @quotationgroups.any?  

    @quotationgroups.includes(:customer, :quotations).each do |group|
    creator = User.find(group.created_by) rescue nil
    %>
    <tr>
        <td><strong><%= group.date.strftime('%d') rescue nil %>.</strong><%= group.date.strftime('%m') rescue nil %></td>
        <td><% if checkrole 'Admin Marketing, General Manager' %><%= link_to group.long_id, edit_quotationgroup_path(group) %> <% else %> <%= group.long_id %> <% end %></td>
        <td>
        <%= group.customer_id.present? ? group.customer.name : (group.customer_name.present? ? group.customer_name : '') %><br>
        <span style="color: grey;"><%= group.customer_pic rescue nil %></span>
        </td>
        <td align="right" style="padding-right: 1rem; "><%= group.quotations.count %></td>
        <td><%= creator.username if !creator.blank? %></td>
        
        <td>
        <%=  status = case 
                when group.customer_approved then 'Disetujui'
                when group.is_sent then 'Dikirim'
                when group.confirmed then 'Terkonfirmasi'
                when group.reviewed then 'Sudah Review'
                else 'Draft'
                end %>
        </td>

        <td class="right">
		<% if checkrole 'Admin Marketing, General Manager' %>
                <%= link_to '&#xf044;'.html_safe, edit_quotationgroup_path(group, :confirmed => true), :class => "edit tipsy", :title => 'Edit' %>
		<% end %>		
                <!-- <%= link_to '&#xf06e;'.html_safe, quotationgroup_path(group), :class => "edit tipsy", :title => 'Show' %> -->
                <!-- <%= link_to '&#xf02f;' .html_safe, print_quotationgroup_path(group), :class => "delete tipsy", :title => 'Print' %> -->
        </td>
    </tr>

    <% end %>	

	    <% else %>	
    
        <tr>
			<td colspan = '6'>
				Tidak ada data penawaran baru
			</td>
        </tr>

    <% end %>

</table>

app/views/approvals/_routes.html.erb
<table class="row-view">
	<tr>
		<th>Nama Jurusan</th>
		<th>Pelanggan</th>
		<th width="200">Alamat Muat</th>
		<th width="200">Alamat Bongkar</th>
		<th>Komoditas</th>
		<th>Jarak (KM)</th>
		<th width="60"></th>
	</tr>

    <% if @new_routes.any? %>

	<% @new_routes.includes(:commodity, :customer).each do |quotation| %>

	<%
	routelocation = Routelocation.where("route_id = ?", quotation.id).order("id DESC").first rescue nil
	%>

	<tr>
		<td><strong><%= link_to quotation.name, edit_route_path(quotation) %></strong></td>
		<td><%= quotation.customer.name rescue nil %></td>
		<td><%= routelocation.address_start rescue nil %></td>
		<td><%= routelocation.address_end rescue nil %></td>
		<td><%= quotation.commodity.name rescue nil %></td>
		<td class="text-right"><%= quotation.distance rescue nil %></td>
		<td class="right" width="60">
			<%= link_to '&#xf044;'.html_safe, edit_route_path(quotation), :class => "edit tipsy", :title => 'Edit' if checkrole 'Admin Operasional, Marketing, Admin Jurusan' %> 
		</td>
	</tr>
	<% end %>	

	    <% else %>	
    
        <tr>
			<td colspan = '6'>
				Tidak ada data jurusan baru
			</td>
        </tr>

    <% end %>

</table>

<small>*jurusan dari penawaran baru</small>

app/views/approvals/_routes_draft.html.erb
<table class="row-view">
	<tr>
		<th>Nama Jurusan</th>
		<th>Pelanggan</th>
		<th width="200">Alamat Muat</th>
		<th width="200">Alamat Bongkar</th>
		<th>Komoditas</th>
		<th>Jarak (KM)</th>
		<th>User</th>
		<th>Status</th>
		<th width="60"></th>
	</tr>

    <% if @draft_routes.any? %>

	<% @draft_routes.includes(:commodity, :customer).each do |route| %>

	<%
	routelocation = Routelocation.where("route_id = ?", route.id).order("id DESC").first rescue nil
	%>

	<tr>
		<td><strong><%= link_to route.name, edit_route_path(route) %></strong></td>
		<td><%= route.customer.name rescue nil %></td>
		<td><%= routelocation.address_start + ' ' rescue nil %><%= route.load_province rescue nil %></td>
		<td><%= routelocation.address_end + ' ' rescue nil %><%= route.unload_province rescue nil %></td>
		<td><%= route.commodity.name rescue nil %></td>
		<td class="text-right"><%= route.distance rescue nil %></td>
		<td><%= route.user.username if !route.user.blank? %></td>
		<td>
			<% text = route.rejected ? 'Rejected by GM' : 'Menunggu Approval GM' %>
			<% color = route.rejected ? 'red' : 'yellow' %>
			<% text_color = route.rejected ? 'white' : 'black' %>
			<a class="cta" style="background: <%= color %>; color: <%= text_color %>; opacity: 1;">
				<%= text %>
			</a>
		</td>
		<td class="right" width="60">
			<%= link_to '&#xf044;'.html_safe, edit_route_path(route), :class => "edit tipsy", :title => 'Edit' if checkrole 'Admin Operasional, Marketing, Admin Jurusan' %> 
		</td>
	</tr>
	<% end %>	

	    <% else %>	
    
        <tr>
			<td colspan = '6'>
				Tidak ada data jurusan baru
			</td>
        </tr>

    <% end %>

</table>

<small>*jurusan baru (tidak melalui penawaran)</small>

<br class="clearfix" />

app/views/approvals/index.html.erb
<%= render "shared/header" %>

<div id="nav">
	<%= render "shared/nav" %>
</div>

<div id="main">
	
	<div id="content-full">

		<h1>Approval / Index</h1>

		<br class="clearfix" />
		<br class="clearfix" />

		<% if checkrole 'Admin Approval, Admin Marketing, General Manager' %>

		<h2 style="font-weight: bold;">Pelanggan Baru</h2>

		<%= render "customers" %>
 
		<br class="clearfix" />

		<% end %>

		<% if checkrole 'Admin Marketing, General Manager, Admin Jurusan, Master Jurusan' %>

		<h2 style="font-weight: bold;">Jurusan Baru (Tidak Melalui Penawaran)</h2>

		<%= render "routes_draft" %>
 
		<br class="clearfix" />

		<% end %>

		<% if checkrole 'Admin Approval, Admin Marketing, General Manager' %>

		<h2 style="font-weight: bold;">Penawaran Baru</h2>

		<%= render "quotations" %>
 
		<br class="clearfix" />

		<% end %>

		<% if checkrole 'Admin Approval Klaim, Admin Marketing, Marketing, General Manager' %>

		<h2 style="font-weight: bold;">Klaim Penagihan</h2>

		<%= render "claims" %>
 
		<br class="clearfix" />

		<% end %>

		<% if checkrole 'Admin Operasional, Admin Sangu, Admin Marketing, Marketing, Operasional BKK, General Manager' %>

		<h2 style="font-weight: bold;">Jurusan Baru (Belum ada sangu)</h2>

		<%= render "routes" %>
 
		<br class="clearfix" />

		<% end %>

	</div>

</div>