config/routes.rb
OfficePuraErp::Application.routes.draw do

  get "debug", to: "dashboards#debug"

  get 'approvals' => 'approvals#index'

  resources :legalities do
    member do
      get 'enable'
      get 'disable'
    end
  end

  devise_for :users,
    :controllers => { sessions: 'devise/sessions' },
    :path => "user",
    :path_names => {
      :sign_in => 'login',
      :sign_out => 'logout'
    }

  resources :routetrains do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :routeships do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :customers do
    member do
      get 'enable'
      get 'disable'
      get 'addroute'
      get 'addcontract'
      get 'clone'
      get 'gm_approve'
    end
    collection do
      get "customer_terms" => "customers#customer_terms"
    end
  end

  resources :customernotes, only: [:create, :update, :destroy]

  get 'contracts/addnew' => 'contracts#addnew'
  resources :contracts do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :suppliers do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :staffs do
    member do
      get 'enable'
      get 'disable'
    end
  end

  get 'drivers/blacklist' => 'drivers#blacklist'
  get 'drivers/history' => 'drivers#history'

  resources :drivers do
    member do
      get 'enable'
      get 'disable'
      get 'blacklisted'
      get 'whitelisted'
    end

    collection do
      get "create_bank_expense_group"
      get "clone"
      get "save_clone"
    end
  end
  
  get 'helpers/blacklist' => 'helpers#blacklist'
  resources :helpers do
    member do
      get 'enable'
      get 'disable'
    end

    collection do
      get "create_bank_expense_group"
    end
  end

  resources :isotanks do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :containers do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :operators do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :products do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :warehouses do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :productgroups do
    member do
      get 'enable'
      get 'disable'
    end
  end

  get 'routes/addnew' => 'routes#addnew'
  resources :routes do
    member do
      get 'enable'
      get 'disable'
      get 'copy'
      get 'approve'
      get 'reject'
      get 'revision'
    end
    collection do
      get "index_api"
      get "index_api_detailed"
      get "managements"
    end
  end

  resources :claimmemos do
    member do
      get 'spv_approve'
      get 'load_approve'
      get 'unload_approve'
      get 'marketing_approve'
      get 'gm_approve'
    end
  end

  get 'quotationgroups/reports' => 'quotationgroups#reports'

  resources :quotationgroups do
    member do
      get "print"
      get "approve_customer"
      get "approve_sent"
      get "approve_confirm"
      get "approve_review"
    end
    collection do
      get 'confirmed' => 'quotationgroups#indexconfirm'
      get "getcustomer/:value" => 'quotationgroups#getcustomer'
      get "getquotation/:id" => 'quotationgroups#getquotation'
      get "index_api"
      get "indexconfirm_api"
      post "confirmation"
    end
  end

  get 'quotations/confirmed' => 'quotations#indexconfirm'
  resources :quotations do
    member do
      get 'enable'
      get 'disable'
      get "copy"
    end
    collection do
      get "index_api"
      get "indexconfirm_api"
      post "confirmation"
    end
  end
 
  match 'vehicles/index_asset' => 'vehicles#index_asset'
  post 'vehicles/update_asset' => 'vehicles#update_asset'
  get 'vehicles/history' => 'vehicles#history'

  resources :vehicles do
    member do
      get 'enable'
      get 'disable'
      get 'edit_asset'
    end
  end

  resources :vehiclelogs

  match 'vehiclelogs/new/:vehicle_id' => 'vehiclelogs#new'
  match "vehicledates" => "vehiclelogs#vehicledates"

  resources :vehiclegroups do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :assets do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :commodities do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :assetgroups

  resources :allowances
  post 'allowances/updateitems' => 'allowances#updateitems'

  resources :tirebudgets
  post 'tirebudgets/updateitems' => 'tirebudgets#updateitems'

  resources :settings

  match 'generalexpenses/new(/:officeexpense_id)' => 'generalexpenses#new'
  post 'generalexpenses/create' => 'generalexpenses#create'
  resources :generalexpenses do
    member do
      get 'enable'
      get 'disable'
    end
  end

  get 'officeexpenses/getofficeexpensegroup/:group_id' => 'officeexpenses#getofficeexpensegroup'
  get 'officeexpenses/getbankexpensegroup/:bankgroup_id' => 'officeexpenses#getbankexpensegroup'

  get 'bankinvoices/getbankexpensegroup/:group_id' => 'bankinvoices#getbankexpensegroup'

  get 'bankexpenses/getbankexpensegroupdebit/:group_id' => 'bankexpenses#getbankexpensegroupdebit'
  get 'bankexpenses/getbankexpensegroupcredit/:group_id' => 'bankexpenses#getbankexpensegroupcredit'

  get 'events/get_event_by_customer/:customer_id' =>'events#get_event_by_customer'
  get 'events/getdodetail' => 'events#getdodetail'

  resources :mechaniclogs do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :shipexpenses do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :officeexpenses do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :officebankexpenses

  resources :officeexpensegroups do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :bankexpenses do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :bankinvoices do
    member do
      get 'verified'
      get 'disable'
      get 'print'
    end
  end

  resources :bankexpensegroups do
    member do
      get 'enable'
      get 'disable'
      get 'inReportEnable'
      get 'inReportDisable'
    end
  end

  resources :offices do
    member do
      get 'enable'
      get 'disable'
    end
  end

  get 'invoices/printspk/:id' => 'invoices#printspk'

  match 'invoices/add_ship' => 'invoices#indexaddship'
  match 'invoices/add_ship/:invoice_id' => 'invoices#add_ship'
  post 'invoices/updateship/' => 'invoices#updateship'

  match 'invoices/add_train' => 'invoices#indexaddtrain'
  match 'invoices/add_train/:invoice_id' => 'invoices#add_train'
  post 'invoices/updatetrain/' => 'invoices#updatetrain'

  get 'invoices/add_container' => 'invoices#indexaddcontainer'
  get 'invoices/add_container/:invoice_id' => 'invoices#add_container'
  post 'invoices/updatecontainer/' => 'invoices#updatecontainer'

  match 'invoices/add_weight' => 'invoices#indexaddweight'
  match 'invoices/add_weight/:invoice_id' => 'invoices#add_weight'
  post 'invoices/updateaddweight/' => 'invoices#updateaddweight'

  match 'invoices/updatedata/:invoice_id' => 'invoices#updatedata', as: 'updatedata'
  post 'invoices/updatedatabkk/' => 'invoices#updatedatabkk'

  #kosonganProduktif
  match 'invoices/kosongan_prod' => 'invoices#kosongan_prod'
  match 'invoices/add_kosongan' => 'invoices#add_kosongan'
  post 'invoices/createkosongan/' => 'invoices#createkosongan', as: 'createkosongan'

  #kosongan non Produktif
  match 'invoices/kosongan_approval' => 'invoices#kosongan_approval'
  match 'invoices/kosongan_approve(/:invoice_id)' => 'invoices#kosongan_approve'
  post 'invoices/kosongan_confirm/' => 'invoices#kosongan_confirm'

  match 'invoices/trainrequest' => 'invoices#indextrainrequest'

  match 'invoices/indexadd' => 'invoices#indexadd'
  match 'invoices/add(/:invoice_id)' => 'invoices#add'
  match 'invoices/indexinvoicetrain' => 'invoices#indexinvoicetrain'
  match 'invoices/adddriver(/:invoice_id)' => 'invoices#adddriver'
  post 'invoices/updateinvoice/' => 'invoices#updateinvoice'
  match 'invoices/print/:invoice_id' => 'invoices#print'
  match 'invoices/form_event' => 'invoices#form_event'
  match 'invoices/kosongan' => 'invoices#kosongan'

  match 'invoices/newupdated' => 'invoices#new_updated', as: "newupdate_invoice"
  match 'invoices/isotank' => 'invoices#isotank', as: "invoice_isotank"
  match 'invoices/kereta' => 'invoices#kereta', as: "invoice_train"
  match 'invoices/kapal' => 'invoices#kapal', as: "invoice_ship"
  match 'invoices/:invoice_id/editupdated' => 'invoices#edit_updated'

  resources :invoices do
    member do
      get 'enable'
      get 'disable'
      get 'step2'
      get 'confirmation'
      get 'printversion'
      get 'cancelmarketing'
    end

    collection do
      get "isotank"
    end
  end

  resources :invoicetrains

  resources :invoicetests do
    member do
      get 'enable'
      get 'disable'
      get 'step2'
      get 'confirmation'
      get 'printversion'
    end
  end

  resources :eventmemos do
    member do
      get 'enable'
      get 'disable'

      get "print"
    end
  end

  resources :eventcleaningmemos do
    member do
      get 'enable'
      get 'disable'
      get "print"
    end
  end

  resources :operators do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :trainexpenses do
    collection do
      get 'download_excel'
    end
    member do
      get 'enable'
      get 'disable'
      get "print"
    end
  end

  resources :insurancevendors do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :insuranceexpenses do
    member do
      get 'enable'
      get 'disable'
      get "print"
    end
  end

  match 'vendors/driver_activities' => 'vendors#driver_activities'

  resources :vendors do
    member do
      get 'enable'
      get 'disable'
    end
  end

  resources :vendorvehicles do
    member do

app/models/routetrain.rb
class Routetrain < ActiveRecord::Base

	belongs_to :operator
	belongs_to :origin_station, class_name: "Station"
	belongs_to :destination_station, class_name: "Station"

	has_many :trainexpenses
	has_many :invoices

	# Setup accessible (or protected) attributes for your model
	attr_accessible :enabled, :deleted, :name, :container_type, :size,
	:operator_id, :origin_station_id, :destination_station_id, :price_per, :gst_tax, :total

	validates :name, presence: true
	validates :operator_id, presence: true
	validates :destination_station_id, presence: true
	validates :origin_station_id, presence: true

	scope :active, lambda {where(:enabled => true, :deleted => false)}

end

app/controllers/routetrains_controller.rb
class RoutetrainsController < ApplicationController
	include ApplicationHelper
	layout "application"
  before_filter :authenticate_user!, :set_section, :set_role
  protect_from_forgery :except => [:update_asset]

  def set_section
    @section = "masters"
    @where = "routetrains"

    @contype = ["ISOTANK 20FT", "ISOTANK 40FT", "ISOTANK EMPTY 20FT", "ISOTANK EMPTY 40FT", "DRY CONTAINER EMPTY 20FT", "DRY CONTAINER 20FT", "DRY CONTAINER EMPTY 40FT", "DRY CONTAINER 40FT"]

    @consize = ["20FT", "40FT"]
  end

  def set_role
    @user_role = 'Admin Operasional, Admin HRD, Admin Keuangan, Admin Kendaraan, Admin Jurusan'
  end

  def index
    role = cek_roles @user_role
    if role
      @routes = Routetrain.active.order(:name)
      respond_to :html
    else
      redirect_to root_path()
    end
  end

  def new
    @routetrain = Routetrain.new
    @routetrain.enabled = true
    respond_to :html
  end

  def edit
    @routetrain = Routetrain.find(params[:id])
    respond_to :html
  end

  def create
    inputs = params[:routetrain]
    @routetrain = Routetrain.new(inputs)
    if @routetrain.save
      redirect_to(routetrains_url(), :notice => 'Data Jurusan Kereta sukses ditambah.')
    else
      redirect_to(new_routetrain_url(), :notice => 'Data Jurusan Kereta gagal ditambah. Data Harus Lengkap.')
    end
  end

  def update
    inputs = params[:routetrain]
    @routetrain = Routetrain.find(params[:id])
    if @routetrain.update_attributes(inputs)
      @routetrain.save
      redirect_to(edit_routetrain_url(@routetrain), :notice => 'Data Jurusan Kereta sukses disimpan.')
    else
      redirect_to(edit_routetrain_url(@routetrain), :notice => 'Data Jurusan Kereta gagal diedit. Data Harus Lengkap.')
    end
  end

  def destroy
    @routetrain = Routetrain.find(params[:id])
    @routetrain.deleted = true
    @routetrain.save
    redirect_to(routetrains_url)
  end

  def enable
    @routetrain = Routetrain.find(params[:id])
    @routetrain.update_attributes(:enabled => true)
    redirect_to(routetrains_url)
  end

  def disable
    @routetrain = Routetrain.find(params[:id])
    @routetrain.update_attributes(:enabled => false)
    redirect_to(routetrains_url)
  end
end

app/views/routetrains/_form.html.erb
<%= form_for(@routetrain) do |f| %>


  <div class="field-row first">
    <%= f.label :operator_id, "Operator" %>
    <select id="routetrain_operator_id" name="routetrain[operator_id]" class="chzn-select half">
      <option value="0">- Operator -</option>
      <% Operator.train.active.order(:abbr).each do |operator| %>
      <option value="<%=operator.id%>"<%= operator.id == @routetrain.operator_id ? ' selected="selected"' : '' %>><%=operator.abbr%></option>
      <% end %>
    </select>
  </div>

	<div class="field-row">
    <%= f.label :name, "Nama Jurusan" %>
    <%= f.text_field :name %>
	</div>

  <div class="field-row">
    <%= f.label :container_type, "Tipe Kontainer"  %>
    <%= f.select :container_type, options_for_select(@contype.collect {|w| [w, w]}, (params[:container_type].present? ? params[:type] : @routetrain.container_type)), {}, { :class => 'half chzn-select' } %>
  </div>

  <div class="field-row">
    <%= f.label :size, "Ukuran"  %>
    <%= f.select :size, options_for_select(@consize.collect {|w| [w, w]}, (params[:size].present? ? params[:type] : @routetrain.size)), {}, { :class => 'half chzn-select' } %>
  </div>

  <div class="field-row first">
    <%= f.label :origin_station_id, "Stasiun Awal" %>
    <select id="routetrain_origin_station_id" name="routetrain[origin_station_id]" class="chzn-select half">
      <option value="0">- Stasiun Awal -</option>
      <% Station.active.each do |station| %>
      <option value="<%=station.id%>"<%= station.id == @routetrain.origin_station_id ? ' selected="selected"' : '' %>><%=station.name%></option>
      <% end %>
    </select>
  </div>

  <div class="field-row first">
    <%= f.label :destination_station_id, "Stasiun Tujuan" %>
    <select id="routetrain_destination_station_id" name="routetrain[destination_station_id]" class="chzn-select half">
      <option value="0">- Stasiun Tujuan -</option>
      <% Station.active.each do |station| %>
      <option value="<%=station.id%>"<%= station.id == @routetrain.destination_station_id ? ' selected="selected"' : '' %>><%=station.name%></option>
      <% end %>
    </select>
  </div>

  <div class="field-row continue">
    <%= f.label :price_per, "Tarif" %>
    <%= f.text_field :price_per, :class => 'half', :onkeypress => 'javascript:return isNumberKey(this);', value: @routetrain.price_per.to_i %>
  </div>
  <div class="actions">
    <%= f.submit "Simpan Data", :class => 'left' if checkrole 'Admin Jurusan' %>
    <a class="back left" href="<%=routetrains_path%>">Kembali ke Index</a>
  </div>
<% end %>

app/views/routetrains/edit.html.erb
<%= render "shared/header" %>

<div id="nav">
	<%= render "shared/nav" %>
</div>

<div id="main">
	<div id="content-full">
		<a class="btn-txt cancel" href="<%= routetrains_path %>"><i class="icon-remove"></i> Kembali</a>

		<h1>Master / <a href="<%=routetrains_path%>">Jurusan Kereta</a> / Tambah</h1>

		<%= render "form" %>
		<br class="clearfix" />
	</div>
</div>

app/views/routetrains/index.html.erb
<%= render "shared/header" %>

<div id="nav">
		<%= render "shared/nav" %>
	</div>

<div id="main">

	<div id="content-full">
		<% if checkrole 'Master Jurusan' %>
			<a class="btn-txt right" href="<%=new_routetrain_path%>"><i class="icon-plus-sign"></i> &nbsp;Tambah Jurusan</a>
		<% end %>

		<h1>Master / <a href="<%=routetrains_path%>">Jurusan Kereta</a> / Index</h1>

		<br class="clearfix"/>

			<table class="tablesorter row-view tablesorterFilters">
				<thead>
				<tr>
						<th>Nama Jurusan</th>
						<th>Tipe</th>
						<th>ST. Asal</th>
						<th>ST. Tujuan</th>
						<th>Operator</th>
						<% if checkrole 'Master Jurusan'%> 
						<th>Harga</th>
						<% end %>
						<th width="60" class="{sorter: false, filter: false} sorter-false">Aktif</th>
						<th width="60" class="{sorter: false, filter: false} sorter-false"></th>
					</tr>
				</thead>

				<tbody>
				<% @routes.each do |route| %>
				<tr>
					<td><% if checkrole 'Master Jurusan' %><%= link_to route.name, edit_routetrain_path(route) %> <% else %> <%= route.name %> <% end %></td>
					<td><%= route.container_type %></td>
					<td><%= route.origin_station.name %></td>
					<td><%= route.destination_station.name %></td>
					<td><%= route.operator.abbr rescue nil %></td>
					<% if checkrole 'Master Jurusan'%> 
					<td><%= to_currency(route.price_per) rescue nil %></td>
					<% end %>
					<% if route.enabled %>
						<td><% if checkrole 'Master Jurusan'%> <%= link_to '&#xf058;'.html_safe, disable_routetrain_path(route), :class => 'enabled tipsy', :title => 'Non Aktifkan' %><% else %><%= link_to '&#xf058;'.html_safe, '', :class => 'enabled tipsy' %><% end %></td>
					<% else %>
						<td><% if checkrole 'Master Jurusan'%> <%= link_to '&#xf057;'.html_safe, enable_routetrain_path(route), :class => 'disabled tipsy', :title => 'Aktifkan' %><% else %><%= link_to '&#xf057;'.html_safe, '', :class => 'disabled tipsy' %><% end %></td>
					<% end %>
					<td class="right" width="60">
						<% if checkrole 'Master Jurusan' %>
							<%= link_to '&#xf044;'.html_safe, edit_routetrain_path(route), :class => "edit tipsy", :title => 'Edit' %>
						<% end %> 
						<%= link_to '&#xf00d;'.html_safe, route, :class => "delete tipsy", :title => 'Hapus', :confirm => 'Apakah anda yakin?', :method => :delete if current_user.owner %>
					</td>
				</tr>
				<% end %>	
				</tbody>
			</table>

		<br class="clearfix"/>

		<div class="actions">
			<% if checkrole 'Master Jurusan' %>
				<a class="btn-txt right" href="<%=new_routetrain_path%>"><i class="icon-plus-sign"></i> &nbsp;Tambah Jurusan</a>
			<% end %>
		</div>

	</div>

</div>

app/views/routetrains/new.html.erb
<%= render "shared/header" %>

<div id="nav">
	<%= render "shared/nav" %>
</div>

<div id="main">
	<div id="content-full">
		<a class="btn-txt cancel" href="<%=routetrains_path%>"><i class="icon-remove"></i> Kembali</a>

		<h1>Master / <a href="<%=routetrains_path%>">Jurusan Kereta</a> / Tambah</h1>

		<%= render "form" %>
		<br class="clearfix" />
	</div>
</div>