config/routes.rb
  get 'invoices/getvehiclegroup/:vehicle_id' => 'invoices#get_vehiclegroup'
  get 'invoices/getvehicles/:vehiclegroup_id' => 'invoices#get_vehicles'
  get 'invoices/getvehicle/:vehicle_id' => 'invoices#get_vehicle'
  get 'invoices/getvehiclesbyofficeid/:office_id' => 'invoices#get_vehicles_by_office_id'
  get 'invoices/gettanktype/:cargotype' => 'invoices#get_tanktype'

  get 'events/estimate_tonage/:price_per_type' => 'events#getestimatedtonage'

  get 'invoices/get_trainroute/:operator_id' => 'invoices#get_trainroute'
  get 'invoices/get_trainroute2/:operator_id' => 'invoices#get_trainroute2'
  get 'invoices/get_shiproute/:operator_id' => 'invoices#get_shiproute'
  get 'invoices/get_shiproute2/:operator_id' => 'invoices#get_shiproute2'
  get 'invoices/getroutesonly/:customer_id' => 'invoices#get_routesonly'

  get 'invoices/getroutes/:customer_id' => 'invoices#get_routes'
  get 'reports/getroutetrains/:operator_id' => 'reports#get_routetrains'
  get 'invoices/getroutesbyoffice/:office_id' => 'invoices#get_routesbyoffice'

  get 'invoices/getrouteswithtype/:customer_id/:transporttype' => 'invoices#get_routeswithtype'
  get 'invoices/getroutes2/:customer_id/:type' => 'invoices#get_routes2'
  get 'invoices/get_routesonly/:customer_id' => 'invoices#get_routesonly'
  get 'invoices/getdriverphone/:driver_id' => 'invoices#get_driverphone'


  get 'invoices/getallowances/:route_id/:vehicle_id/:trip/:quantity/:ishelper/:ispremi' => 'invoices#get_allowances'

  match 'invoicereturns/index_confirmed' => 'invoicereturns#index_confirmed'
  match 'invoicereturns/add/(:invoice_id)' => 'invoicereturns#add'
  match 'invoicereturns/train/(:invoice_id)' => 'invoicereturns#train'
  match 'invoicereturns/index_confirmedtrain' => 'invoicereturns#index_confirmedtrain'

  post 'invoicereturns/saveadd' => 'invoicereturns#saveadd'
  resources :invoicereturns

  match 'receiptorders/new/:productorder_id' => 'receiptorders#new'
  match 'receiptreturns/new/:invoicereturn_id' => 'receiptreturns#new'
  match 'receiptpremis/new/:invoice_id' => 'receiptpremis#new'
  match 'receiptexpenses/new/:officeexpense_id' => 'receiptexpenses#new'
  match 'receiptdrivers/new/:driverexpense_id' => 'receiptdrivers#new'
  match 'receiptincentives/new/:invoice_id' => 'receiptincentives#new'
  match 'driverexpenses/getdrivers/:type' => 'driverexpenses#getdrivers'

  get 'taxinvoiceitems/index-2' => 'taxinvoiceitems#index2'

  resources :receiptincentives
  resources :receiptpremis
  resources :receiptorders
  resources :receipts
  resources :receiptexpenses
  resources :receiptreturns
  resources :receiptdrivers
  resources :driverexpenses
  resources :taxinvoiceitems
  resources :users
  resources :driverlogs
  resources :supplierpayments
  resources :assetgroups
  resources :assetorders
  resources :taxgenericinvoices
  resources :ships
  resources :ports
  resources :receipttrains
  resources :receiptships
  resources :receiptinsurances

  resources :mechanics

  match 'assetpayments/new/:assetorder_id' => 'assetpayments#new'
  match 'assetpayments/index_confirmed' => 'assetpayments#index_confirmed'
  resources :assetpayments

  post 'taxinvoices/deletesentdatelog/:id' => 'taxinvoices#delete_sentdatelog'
  get 'taxinvoices/getsentdatelog/:taxinvoice_id' => 'taxinvoices#get_sentdatelog'
  get 'taxinvoices/gettaxinvoiceitems/:taxinvoice_id/:customer_id/:is_wholesale' => 'taxinvoices#gettaxinvoiceitems'
  match 'taxinvoices/downloadexcel/:taxinvoice_id' => 'taxinvoices#downloadexcel'
  post 'taxinvoices/updatepayment' => 'taxinvoices#updatepayment'
  post 'taxinvoices/transfer' => 'taxinvoices#transfer'

  post 'customers/transfer' => 'customers#transfer'

  resources :taxinvoices do
    member do
      get 'print'
      get 'printv2'
      get 'cancelpayment'
      get 'printreceipt'
      get 'clone'
      get 'updatecustomer'
      post 'update_doubtful_note'
    end
    collection do
      get 'downloadmultiexcel'
      post "update_tax"
      get 'generic-vehicles' => 'taxgenericinvoices#generic_vehicles'
      match 'generic/updateitems' => 'taxgenericinvoices#updateitems'
      match 'generic(/:id)' => 'taxgenericinvoices#new'
      get 'generic(/:id)/updatecustomer' => 'taxgenericinvoices#updatecustomer'

      match 'dp_only(/:id)' => 'taxinvoices#newdp'

      post 'updatecustomerinfo' => 'taxinvoices#updatecustomerinfo'
      post 'updatecustomerinfogeneric' => 'taxgenericinvoices#updatecustomerinfo'

      post 'updatepayment' => 'taxinvoices#updatepayment'
      post 'downpayment' => 'taxinvoices#downpayment'
      post 'canceldownpayment' => 'taxinvoices#canceldownpayment'

      post 'secondpayment' => 'taxinvoices#secondpayment'
      post 'cancelsecondpayment' => 'taxinvoices#cancelsecondpayment'

      post 'thirdpayment' => 'taxinvoices#thirdpayment'
      post 'cancelthirdpayment' => 'taxinvoices#cancelthirdpayment'

      post 'fourthpayment' => 'taxinvoices#fourthpayment'
      post 'cancelfourthpayment' => 'taxinvoices#cancelfourthpayment'

      post 'import_excel'
    end
  end

  resources :receipttaxinvitems do
    collection do
      get 'create_receiptinvoice'
      post 'create_receipt'
      post 'update_receipt'
    end
    member do
      get 'print'
      post 'confirm_billing'
      post 'update_printdate'
      get 'detail_excel'
    end
  end

  post "receipttaxinvoices/preview", to: "receipttaxinvoices#preview", as: :preview_receipttaxinvoices
  get '/receipttaxinvoices/download_excel_preview', to: 'receipttaxinvoices#download_excel_preview', as: :download_excel_preview

  resources :receipttaxinvoices do
    collection do
      get 'create_receiptaxinvoice'
      post 'create_receipt'
      post 'update_receipt'
      get 'download_excel'
    end
    member do
      get 'print'
      post 'confirm_billing'
      post 'update_printdate'
      get 'detail_excel'
    end
  end

  resources :taxinvoiceattachments
  get 'taxinvoiceattachments/gettaxinvoicesbycustomer/:customer_id' => 'taxinvoiceattachments#gettaxinvoicesbycustomer'

  match 'bonusreceipts/index_confirmed' => 'bonusreceipts#index_confirmed'

  resources :bonusreceipts do
    member do
      get 'confirmation'
    end
  end

  match 'incentives/index_confirmed' => 'incentives#index_confirmed'
  resources :incentives

  resources :productsales

  get 'sales/getpriceproductsale/:productsale_id' => 'sales#getpriceproductsale'

  resources :sales do
    member do
      get 'confirmation'
    end
  end

  match 'receiptsales/new/:sale_id' => 'receiptsales#new'
  resources :receiptsales

  get 'paymentchecks/new/:supplier_id' => 'paymentchecks#new'
  get 'paymentchecks/indexchecks' => 'paymentchecks#indexchecks'
  resources :paymentchecks

  get 'cashiers/getrequests(/:date)' => 'cashiers#getrequests'
  resources :cashiers

  match 'events/add_dovendor' => 'events#indexadddovendor'
  match 'events/add_dovendor/:event_id' => 'events#add_dovendor'
  match 'events/getdovendor'
  match 'events/getdovroutes/:customer_id' => 'events#getdovroutes'
  match 'events/getdovvendors/:multimoda' => 'events#getdovvendors'
  match 'events/getdovvendorroutes/:vendor_id' => 'events#getdovvendorroutes'
  match 'events/transferdov' => 'events#transferdov'

  get 'events/geteventsv2(/:type)' => 'events#geteventsv2'
  get 'events/getevents(/:type)' => 'events#getevents'

  match 'events/version-2' => 'events#version2'
  get 'events/resync' => 'events#resync'
  get 'events/cancelled' => 'events#cancelled'
  get 'events/get_unpaid_inv' => 'events#get_unpaid_inv'

  match 'events/remove' => 'events#remove'

  resources :events do
    member do
      get 'restore'
    end
    collection do
      get 'getdovendor' => 'events#getdovendor'
    end
  end

  get 'bookings/getbookings(/:type)' => 'bookings#getbookings'
  get 'bookings/report-bookings' => 'bookings#report_bookings'
  resources :bookings

  get 'productrequests/getproductstocks/:product_id' => 'productrequests#getproductstocks'
  get 'productrequests/getrangetires/:productgroup_id/:vehicle_id/:date' => 'productrequests#getrangetires'
  get 'productrequests/getproductbygroupid/:productgroup_id' => 'productrequests#getproductbygroupid'
  get 'productrequests/getproductgroupname/:productgroup_id' => 'productrequests#getproductgroupname'

  resources :productrequests do
    member do
      get 'confirmation'
    end
  end

  match 'productorders/add/' => 'productorders#add'
  get 'productorders/getproductbyid/:product_id' => 'productorders#getproductbyid'
  post 'productorders/updateitem/' => 'productorders#updateitem'
  resources :productorders do
    member do
      get 'confirmation'
      get 'return'
    end
  end

    match 'receipts/new/:invoice_id' => 'receipts#new'
    match 'invoicereturns/new/:invoice_id' => 'invoicereturns#new'
    match 'taxinvoiceitems/new/:invoice_id(/:update)' => 'taxinvoiceitems#new'
    match 'taxinvoiceitems/print(/:invoice_id)' => 'taxinvoiceitems#print'
    post 'taxinvoiceitems/updateitems' => 'taxinvoiceitems#updateitems'
    post 'taxinvoiceitems/rejected' => 'taxinvoiceitems#rejected'
    get 'taxinvoiceitems/getCustomerbyDate/:date' => 'taxinvoiceitems#getCustomerbyDate'
    get 'taxinvoiceitems/vendor_detail/:item_id' => 'taxinvoiceitems#vendor_detail'
    match 'taxinvoices/new(/:customer_id)' => 'taxinvoices#new'
    match 'taxinvoices/updateitems' => 'taxinvoices#updateitems'
    match 'taxinvoices/payment/:taxinvoice_id' => 'taxinvoices#payment'
    match 'taxinvoices/send_email/:taxinvoice_id' => 'taxinvoices#send_email'
    match 'driverlogs/new/:driver_id' => 'driverlogs#new'

  match 'bonusreceipts/new/:invoice_id' => 'bonusreceipts#new'
  post 'bonusreceipts/updateitems' => 'bonusreceipts#updateitems'
  match 'incentives/new/:invoice_id' => 'incentives#new'
  post 'incentives/updateitems' => 'incentives#updateitems'

  match "masters" => "customers#index"
  match "transactions" => "invoices#index"
  match "reports" => "reports#index"

app/models/sale.rb
class Sale < ActiveRecord::Base

  has_many :saleitems
  has_many :receiptsales


  # Setup accessible (or protected) attributes for your model
  attr_accessible :deleted, :date, :description, :user_id, :total, :deleteuser_id

  scope :active, lambda {where(:deleted => false)}

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
	include ApplicationHelper
  	include ActionView::Helpers::NumberHelper
	layout "application", :except => [:getpriceproductsale]
  	before_filter :authenticate_user!, :set_section
  
	def set_section
		@section = "transactions2"
		@where = "sales"
	end

	def index
		@date = params[:date]
		@date = Date.today.strftime('%d-%m-%Y') if @date.nil?
		@sales = Sale.where('date = ?', @date.to_date).order(:id)
		respond_to :html
	end

	def new
		@errors = Hash.new
		@sale = Sale.new
		@sale.date = Date.today.strftime('%d-%m-%Y') if @sale.date.nil?
	end

	def edit
		@errors = Hash.new 
		@sale = Sale.find(params[:id])
		@saleitems = Saleitem.where(:sale_id => @sale.id)
	end

	def create 
		inputs = params[:sale]
		@sale = Sale.new
		@sale.date = inputs[:date]
		@sale.description = inputs[:description]
		@sale.user_id = current_user.id

		if @sale.save
			(1..10).each do |i|
				if inputs["productsaleid_"+ i.to_s].to_i != 0 and inputs["quantity_"+i.to_s].to_i != 0
					saleitem = Saleitem.new
					saleitem.sale_id = @sale.id
					saleitem.productsale_id = inputs["productsaleid_"+i.to_s].to_i
					saleitem.quantity = inputs["quantity_"+i.to_s].to_i

					productsale = Productsale.find(inputs["productsaleid_"+i.to_s].to_i) rescue nil

					saleitem.price_per = productsale.unit_price
					saleitem.total = saleitem.quantity * saleitem.price_per
					saleitem.save
				end
			end
			@sale.total = @sale.saleitems.sum(:total)
			@sale.save	

			redirect_to(confirmation_sale_url(@sale.id), :notice => "Data Penjualan Barang sukses di simpan")
		else
			to_flash(@sale)
      		render :action => "new"	
		end

	end

	def update
		inputs = params[:sale]
		@sale = Sale.find(params[:id])
		@sale.date = inputs[:date]
		@sale.description = inputs[:description]

		if @sale.save
			@sale.saleitems.each do |saleitem|
				if inputs["quantity_"+saleitem.id.to_s].to_i != 0
					saleitem.quantity = inputs["quantity_"+saleitem.id.to_s].to_i

					saleitem.total = saleitem.quantity * saleitem.price_per
					saleitem.save
				end
			end
			@sale.total = @sale.saleitems.sum(:total)
			@sale.save	

			redirect_to(confirmation_sale_url(@sale.id), :notice => "Data Penjualan Barang sukses di simpan")
		else
			to_flash(@sale)
      		render :action => "new"	
		end
	end

	def confirmation
		@errors = Hash.new 
		@sale = Sale.find(params[:id])
		@saleitems = Saleitem.where(:sale_id => @sale.id)
	end

	def getpriceproductsale
		productsale = Productsale.find(params[:productsale_id]) rescue nil
		puts productsale.unit_price
		price = productsale.unit_price.to_i if !productsale.nil?

		render :json => {:success => true, :layout => false,
			:price => price
			}.to_json;
	end

	def destroy
		@sale = Sale.find(params[:id])
		
		if @sale.receiptsales.where(:deleted => false).any?
			redirect_to(sales_url, :notice => 'Penjualan barang No. #' + zeropad(@sale.id) +' tidak dapat dihapus. Harap hapus data yang sudah dikonfirmasi kasir terlebih dahulu.')
		else	

			@sale.deleteuser_id = current_user.id
			@sale.deleted = true
			@sale.save	

			redirect_to(sales_url)
		end

	end
end

app/views/sales/_form-confirmation.erb
<%= form_for(@sale) do |f| %>
	<div class="actions" style="float:left; padding:0 0 30px 20px;">
		<a class="left" href="javascript:print();"><i class="icon-print"></i> Print Normal</a>
    	<a class="back left" href="<%=sales_path%>">Kembali ke Index</a>
  	</div>
	<div class="info-box" style="width:560px; float:left; clear:left;">
		<table class="row-view no-border">
			<tr valign="top">
				<td><strong><%= Setting.find_by_name("Client Name").value.upcase if !Setting.find_by_name("Client Name").nil? %><br /> <%= Setting.find_by_name("Client Address").value if !Setting.find_by_name("Client Address").nil? %></strong></td>
				<td align="right" class="header">Data Penjualan Barang<br/>#<%= zeropad(@sale.id)%></td>
			</tr>
		</table>
		<hr style="width:600px;" />		
		 <table class="row-view no-border">
			<tr>
				<td>Tanggal</td>
				<td><%= @sale.date.strftime('%d-%m-%Y') %></td>
			</tr>
			<tr>
				<td>Keterangan</td>
				<td><%= @sale.description %></td>
			</tr>
		</table>
		<% if @sale.saleitems.any? %>
		<table class="row-view">
			<tr>
				<th width="30">No.</th>
				<th>Nama Barang</th>
				<th width="80" class="right">Jumlah</th>
				<th width="120" class="right">Total<th>
			</tr>
			
			<% @sale.saleitems.each_with_index do |saleitem, i|%>
			<tr>
				<td><%=i+1%>.</td>
				<td><%= saleitem.productsale.name%></td>
				<td align="right"><%= saleitem.quantity.to_i%> <%= saleitem.productsale.unit_name %> </td>
				<td align="right"><%= to_currency(saleitem.total.to_i)%></td>
			</tr>
			<% end %>
			<tr>
				<td></td>
				<td class="total">TOTAL</td>
 				<td></td>
 				<td style="text-align:right;"><span id="strTotal"><%=to_currency(@sale.saleitems.sum(:total))%></span></td> 				
 			</tr>
		</table>	
		<% end %>	
	</div>
	
<% end %>

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
	<div class="field-row first">
		 <label for="date">Tanggal</label>
		 <input type="text" name="sale[date]" class="half date-picker" value="<%= @sale.date.strftime('%d-%m-%Y') if !@sale.date.nil? %>" />
		 <div class="field-row continue">
 			<label for="description">Keterangan</label>
 			<input type="text" name="sale[description]" style="width:350px;" value="<%= @sale.description if !@sale.description.nil?%>" />	 		
 		</div>			
	</div> 

	<table class="row-view">
		<tr>
			<th width="30">No.</th>
			<th>Nama Barang</th>
			<th width="40" class="right">Jumlah</th>
			<th width="40" class="right">Harga</th>
			<th width="40" class="right">Total<th>				
		</tr>
		<% if @sale.saleitems.any? %>
			<% total = 0%>
			<% @sale.saleitems.each_with_index do |item, i | %>
			<tr>
				<td><%=i + 1%></td>
				<td><%= item.productsale.name %></td>
				<td>
					<input type="text" id="quantity_<%=item.id%>" name="sale[quantity_<%=item.id%>]" class="short" style="text-align:right;" onkeypress="javascript:return isDecimalKey(this);" value="<%= item.quantity%>" onchange="javascript: changeTotalProductsale(<%=item.id%>);"/>
				</td>
				<td>
					<input type="text" id="price_<%=item.id%>" name="sale[price_<%=item.id%>]" class="half right none" readonly="readonly" style="text-align:right;" value="<%= to_currency(item.price_per)%>" />
				</td>
				<td>
					<input type="text" id="total_<%=item.id%>" style="text-align:right;" name="sale[total_<%=item.id%>]" readonly="readonly" class="half right none" value="<%= to_currency(item.total) %>" />
				</td>
			</tr>
			<% total += item.total %>
			<% end %>
			<tr>
				<td></td>
				<td></td>
				<td></td>
				<td class="total right">TOTAL</td>
				<td><input type="text" class="half right none" readonly="readonly" id="totalsale" style="text-align:right;" value="<%= to_currency(total)%>"/></td>
			</tr>
		<% else %>
			<% (1..10).each do |i| %>
			<tr>
				<td><%=i%></td>
				<td>
					<select id="productsaleid_<%=i%>" name="sale[productsaleid_<%=i%>]" onchange="javascript:getPriceProductsale(this.value, <%=i%>);" style="width:500px">
						<option value="">- Barang - </option>
						<% Productsale.where(:deleted => false).order(:name).each do |item|%>
						<option value="<%= item.id%>"><%= item.name%></option>
						<% end %>
					</select>
				</td>
				<td>
					<input type="text" id="quantity_<%=i%>" name="sale[quantity_<%=i%>]" class="short" style="text-align:right;" onkeypress="javascript:return isDecimalKey(this);" value="0" 
					onchange="javascript: changeTotalProductsale(<%=i%>);"/>
				</td>
				<td>
					<input type="text" id="price_<%=i%>" name="sale[price_<%=i%>]" class="half right none" readonly="readonly" style="text-align:right;" value="0" />
				</td>
				<td>
					<input type="text" id="total_<%=i%>" style="text-align:right;" name="sale[total_<%=i%>]" readonly="readonly" class="half right none" value="0" />
				</td>
			</tr>
			<% end %>
			<tr>
				<td></td>
				<td></td>
				<td></td>
				<td class="total right">TOTAL</td>
				<td><input type="text" class="half right none" readonly="readonly" id="totalsale" style="text-align:right;" value="0"/></td>
			</tr>
		<% end %>
	<table>
	<div class="actions">
		<a class="back right" href="<%=sales_path%>">Kembali ke Index</a>
		<input type="submit" class="btn right" value="Tambah Data" %>
	</div>
<% end %>

app/views/sales/_showtable.html.erb
<table class="row-view">
	<tr>
		<th width="30">No.</th>
		<th width="50">ID</th>
		<th>Keterangan</th>
		<th width="100" class="right">Total</th>
		<th width="60"></th>
	</tr>

	<% i = 0 %>

	<% @sales.each do |sale| %>
	<% items = "" 
		sale.saleitems.each do |saleitem| 
			items += saleitem.quantity.to_s + " " + saleitem.productsale.unit_name + ": " + saleitem.productsale.name + ", "
		end
		items = items[0...-2]	
	%>
	<% if sale.deleted %>
	<% if current_user.adminrole %>
	<tr class="deleted">
		<td><%= i+=1 %>.</td>
		<td><%= zeropad(sale.id) %></td>
		<td><%= items %></td>
		<td class="red" align="right"><%=to_currency(sale.total)%></td>
		<td class="right">DIHAPUS</td>
	</tr>
	<% end %>
	<% else %>
	<tr>
		<td><%= i+=1 %>.</td>
		<td><%= link_to zeropad(sale.id), edit_sale_path(sale) %></td>
		<td><%= link_to items, edit_sale_path(sale)%></td>
		<td class="green" align="right"><%= to_currency(sale.total) %></td>
		<td class="right">
			<% if sale.receiptsales.active.count == 0 %>
			<%= link_to '&#xf044;'.html_safe, edit_sale_path(sale), :class => "edit tipsy", :title => 'Edit' %> 
			<% end %>
			<a href="<%= confirmation_sale_path(sale)%>" class="delete tipsy" title="Print Penjualan"><i class="icon-print"></i></a>
			<%= link_to '&#xf00d;'.html_safe, sale, :class => "delete tipsy", :title => 'Hapus', :confirm => 'Apakah anda yakin?', :method => :delete %>
		</td>
	</tr>
	<% end %>
	<% end %>
</table>

app/views/sales/_steps.html.erb
<ul id="steps">
  <li <% if step == 1 %> class="on" <% end %>><% if !@sale.id.nil? and @sale.receiptsales.active.count == 0 %><a href="<%=edit_sale_url(@sale)%>"><% end %><span>1</span> Data Penjualan<% if !@sale.id.nil? and @sale.receiptsales.active.count == 0 %></a><% end %></li>
  <li class="separator"><i class="icon-chevron-right"></i></li>
  <li<% if step == 2 %> class="on"<% end %>><% if !@sale.id.nil? %><a href="<%=confirmation_sale_url(@sale)%>"><% end %><span>2</span> Konfirmasi<% if !@sale.id.nil? %></a><% end %></li>
</ul>

app/views/sales/confirmation.html.erb
<%= render "shared/header" %>

<div id="nav">
	<%= render "shared/nav" %>
</div>

<div id="main">
	<div id="content-full">
		<a class="btn-txt cancel" href="<%=sales_path%>"><i class="icon-remove"></i> Batal</a>

		<h1 class="header-hide">Transaksi / <a href="<%=sales_path%>">Penjualan Barang Bekas</a> / Index</h1>

		<br class="clearfix" />
			<%= render "steps", :step => 2 %>
			<%= render "form-confirmation" %>
		<br class="clearfix" />
	</div>
</div>

app/views/sales/edit.html.erb
<%= render "shared/header" %>

<div id="nav">
	<%= render "shared/nav" %>
</div>

<div id="main">
	<div id="content-full">
		<a class="btn-txt cancel" href="<%=sales_path%>"><i class="icon-remove"></i> Batal</a>

		<h1>Transaksi / <a href="<%=sales_path%>">Penjualan Barang Bekas</a> / Edit</h1>

		<br class="clearfix" />
			<%= render "steps", :step => 1 %>
			<%= render "form" %>
		<br class="clearfix" />
	</div>
</div>

app/views/sales/index.html.erb
<%= render "shared/header" %>
<div id="nav">
	<%= render "shared/nav" %>
</div>
<div id="main">
	
	<div id="content-full">
		<a class="btn print" href="<%=new_sale_path%>"><i class="icon-plus-sign"></i> &nbsp;Tambah</a>
		<h1>Transaksi / <a href="<%=sales_path%>">Penjualan Barang Bekas</a> / Index</h1>

		<br class="clearfix" />

		<div id="filter">
			<form id="filterform" name="filterform" action="" method="get">
			<div class="field-row continue">
				<label for="date">Tanggal</label>
				<input type="text" name="date" class="half date-picker" value="<%=@date%>" onchange="javascript: submitFormFilter();" />
			</div>
			</form>
		</div>
		<br class="clearfix" />
			<%= render "showtable" %>
		<br class="clearfix" />
		<div class="actions">
			<a class="btn-txt right" href="<%=new_sale_path%>"><i class="icon-plus-sign"></i> &nbsp;Tambah</a>
		</div>
	</div>	
</div>

app/views/sales/new.html.erb
<%= render "shared/header" %>

<div id="nav">
	<%= render "shared/nav" %>
</div>

<div id="main">
	<div id="content-full">
		<a class="btn-txt cancel" href="<%=sales_path%>"><i class="icon-remove"></i> Batal</a>

		<h1>Transaksi / <a href="<%=sales_path%>">Penjualan Barang Bekas</a> / Tambah</h1>

		<br class="clearfix" />
			<%= render "steps", :step => 1 %>
			<%= render "form" %>
		<br class="clearfix" />
	</div>
</div>